#!/bin/bash

source ./paths.sh
rm -rf $backupdir

for i in "${paths[@]}"
do
    dir=$(dirname $i)
    mkdir -p $backupdir/$dir
    cp -r ~/$i $backupdir/$dir
done

find ./files -type f -name '*history*' -exec rm {} +
find ./files -type f -name '*tagged*' -exec rm {} +
find ./files -type f -name '*cache*' -exec rm {} +

# no ` and 0-9 bookmarks synced
ranger_bookmarks=./files/.config/ranger/bookmarks
grep '^[^0-9]' <"$ranger_bookmarks" | tail - -n +2> "$ranger_bookmarks.tmp" && mv "$ranger_bookmarks.tmp" "$ranger_bookmarks"
