#!/bin/bash

source ./places.sh
rm -rf $backupdir
mkdir -p $backupdir/.config

for i in "${places[@]}"
do
    # echo ~/$i
    # echo $(realpath $backupdir/$(dirname $i))
    cp -r ~/$i $(realpath $backupdir/$i)
done
