#!/bin/bash

source ./paths.sh
rm -rf $backupdir

for i in "${paths[@]}"
do
    dir=$(dirname $i)
    mkdir -p $backupdir/$dir
    cp -r ~/$i $backupdir/$dir
done

find ./files -type f -name '*history*' -exec rm {} +
find ./files -type f -name '*tagged*' -exec rm {} +
find ./files -type f -name '*cache*' -exec rm {} +

# no always changing line of recent jump code
ranger_bookmarks=./files/.config/ranger/bookmarks
tail -n +2 "$ranger_bookmarks" > "$ranger_bookmarks.tmp" && mv "$ranger_bookmarks.tmp" "$ranger_bookmarks"
