#!/bin/bash

I3_DIR=~/.config/i3

WORKSPACENAME=$1

if i3-msg -t get_workspaces | jq ".[] | .name" | grep -q -w "$WORKSPACENAME"; then
    i3-msg "workspace $WORKSPACENAME"
else
    i3-msg "workspace $WORKSPACENAME"
    i3-msg 'layout tabbed'
    # for i in "${@:2}"
    # do
    #     $($i)
    # done
fi
