#!/bin/bash

I3_DIR=~/.config/i3
WORKSPACENAME=$1
LAYOUT=$2
TERM=$3

cava="$TERM -e cava"
pandora="$TERM -e pianobar"
player="chromium --app=https://play.google.com/music/listen#/ap/auto-playlist-thumbs-up"

$I3_DIR/init_layout "$WORKSPACENAME" "$LAYOUT" "$cava" "$pandora" "$player"
