#!/bin/bash

I3_DIR=~/.config/i3
WORKSPACENAME=$1
LAYOUT=$2
TERMINAL=$3

visualizer="$TERMINAL -e vis"
lyrics="sleep 0.4 && $TERMINAL -e nvim"
pandora="sleep 0.8 && $TERMINAL -e pianobar"

$I3_DIR/init_layout "$WORKSPACENAME" "$LAYOUT" "$player" "$visualizer" "$pandora" "$lyrics" "$focus"

