#!/bin/bash

I3_DIR=~/.config/i3
WORKSPACENAME=$1
LAYOUT=$2
TERMINAL=$3

visualizer="$TERMINAL -c visualizer -e vis"
lyrics="$TERMINAL -c subs -e nvim -c ':call ScratchBuffer() | setl spell'"
pandora="$TERMINAL -c pianobar -e pianobar"
focus="i3 '[class=\"pianobar\"]' focus"

$I3_DIR/init_layout "$WORKSPACENAME" "$LAYOUT" "$player" "$visualizer" "$pandora" "$lyrics" "$focus"

