#!/bin/bash

outputdir="./output"
mkdir -p $outputdir
inputfilename=$1

pdflatex -interaction nonstopmode -file-line-error -output-directory="$outputdir" "$inputfilename"

inotifywait -m -e modify --exclude '^.*\.(pdf|log|toc|aux)$' --format %f . | while read f;
do 
    echo $f modified 
    pdflatex -interaction nonstopmode -file-line-error -output-directory="$outputdir" "$inputfilename"
done
