#!/bin/bash

command="$*"

executable=$(echo $command | awk '{print $1}')
if type $executable > /dev/null; then
    dir=~/apps/repl/$executable
    mkdir -p $dir

    if [[ "$command" =~ ^trans.* ]]
    then
        command="$command -no-ansi"
    fi

    while read input; do
        # $command "$input" | nvim -
        filepath=$dir/$(echo $input | tr ' ' _).txt
        # if [ ! -f $filepath ]; then
        #     eval "$command $input" > $filepath
        # fi
        output=$(eval "$command $input")
        if [[ ! -z $output ]]
        then
            echo $output > $filepath
            $EDITOR $filepath
        fi
    done
fi

