#!/bin/bash

LAYOUT_PATH=~/.config/i3/layouts
WORKSPACENAME=$1
LAYOUT=$2
I3_DIR=$3
TERM=$4

cava="$TERM -e cava"
pandora="chromium --app=https://www.pandora.com"
player="chromium --app=https://play.google.com/music/listen#/ap/auto-playlist-thumbs-up"

$I3_DIR/workspace_init "$WORKSPACENAME" "$LAYOUT" "$cava" "$pandora" "$player"
